application: p03-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"